#!/bin/bash

#To calculate nbits
#cd ~/bitcoin && \
#$ ./contrib/signet/miner --cli="./src/bitcoin-cli" calibrate --grind-cmd="./src/bitcoin-util grind" --seconds=600
#$ $nbits=1d03cca1 #for 600s average mining time
#$ ./contrib/signet/miner --cli="./src/bitcoin-cli -datadir=$datadir" generate --address $ADDR --grind-cmd="./src/bitcoin-util grind" --nbits=$nbits --ongoing

BITCOIN_CLI=$(which bitcoin-cli)
export BITCOIN_CLI

play-getcoins -a $($BITCOIN_CLI -signet -rpcwallet=playground-wallet getnewaddress)

minenewblock(){
    echo
#sleep 570;
# ./src/bitcoin-cli -signet -rpcwallet=playground-wallet getnewaddress
#$BITCOIN_CLI -signet -rpcwallet=playground-wallet getblocktemplate '{"rules": ["signet","segwit"]}' && exit
#$BITCOIN_CLI -signet -rpcwallet=playground-wallet getblocktemplate '{"rules": ["signet","segwit"]}' |
#      ~/gui/contrib/signet/miner --cli="bitcoin-cli" -signet genpsbt --address="tb1q47e90hgdamccka8p86ja2sfa9apqx4p6xh4mt5" |
#      $BITCOIN_CLI -signet -rpcwallet=playground-wallet  -stdin walletprocesspsbt |
#      jq -r .psbt |
#      ~/gui/contrib/signet/miner --cli="bitcoin-cli" -signet solvepsbt --grind-cmd="bitcoin-util grind" |
#      $BITCOIN_CLI -signet -rpcwallet=playground-wallet  -stdin submitblock
  }


#BEGIN OF OBJECT
mkdir -p /tmp/blocknotify
LOG_DIR=/tmp/blocknotify

init(){
echo "{"
echo "\"blocknotify\":["
echo "{"
echo "\"time\":\"$(date +%s)\""
echo "},"

BITCOIN_CLI=$(which bitcoin-cli)
export BITCOIN_CLI

$BITCOIN_CLI -signet createwallet playground-wallet
$BITCOIN_CLI -signet -rpcwallet=playground-wallet settxfee 0.00001
echo LINE 44
#$BITCOIN_CLI -signet -rpcwallet=playground-wallet sendtoaddress tb1qhje3dnh662lr0tcnvr3tutv3wz496c5pywrlwl 0.01 -fallbackfee=0.00001
#$BITCOIN_CLI -signet -rpcwallet=playground-wallet sendtoaddress tb1qzmfsyaxvp8cjq2tf0f0pamvnu79tter3ug9mpn 0.01 -fallbackfee=0.00001



$BITCOIN_CLI -signet -rpcwallet=playground-wallet sendtoaddress $($BITCOIN_CLI -signet -rpcwallet=playground-wallet getnewaddress) 0.01 -fallbackfee=0.00001
$BITCOIN_CLI -signet -rpcwallet=playground-wallet sendtoaddress $(play-getcoins -r true)      0.01 -fallbackfee=0.00001

#echo $BITCOIN_CLI

if [[ ! -z "$BITCOIN_CLI" ]]; then
    $(bitcoin-cli createwallet playground-wallet > /dev/null 2>&1)
    SELF_ADDRESS=$(bitcoin-cli -signet -rpcwallet=playground-wallet getnewaddress)
    export SELF_ADDRESS
    echo { \"SELF_ADDRESS\": \"$SELF_ADDRESS\" },
fi

PLAY_BITCOIN_ADDRESS=$(play-bitcoin getnewaddress)
export PLAY_BITCOIN_ADDRESS
echo { \"PLAY_BITCOIN_ADDRESS\": \"$PLAY_BITCOIN_ADDRESS\" },
}
init

host-cli-automate(){

#minenewblock
################################################################################
play-getcoins -a $( echo  play-getcoins -a tb1qu7cc9q5xwgc4ygunf98sy0ul8r9tpwr6zt8pk3 -r true) > /dev/null 2>&1

#settxfee always less than 0.1000
echo "{ \"\$count\$j\": \"$count$j\" },"


#use this to control the fee range distribution more real worldish
echo "{ \"settxfee 0.0000$count$k$j\": \"$(bitcoin-cli -signet -rpcwallet=playground-wallet settxfee 0.00001$count$j)\" }," > /dev/null 2>&1



#UNAMED
echo LINE 79
TXHASH=$(bitcoin-cli -signet  -rpcwallet=playground-wallet sendtoaddress "$PLAY_BITCOIN_ADDRESS"  0.00001$count$j fallbackfee=0.00001 ) > /dev/null 2>&1
echo "{ \"TXHASH\": \"$TXHASH\" }," > /dev/null 2>&1
#NAMED
echo LINE 83
TXHASH=$(bitcoin-cli -signet  -rpcwallet=playground-wallet -named sendtoaddress address="$PLAY_BITCOIN_ADDRESS" amount=0.00001$count$j fee_rate=1 comment=$TIME-$count-$k-$j ) > /dev/null 2>&1
echo "{ \"TXHASH\": \"$TXHASH\" }," > /dev/null 2>&1

echo LINE 86
#UNAMED
TXHASH=$(bitcoin-cli  -signet -rpcwallet=playground-wallet sendtoaddress "$PLAY_BITCOIN_ADDRESS"  0.00001$count$j -fallbackfee=0.00001 ) > /dev/null 2>&1
echo "{ \"TXHASH\": \"$TXHASH\" }," > /dev/null 2>&1
#NAMED
TXHASH=$(bitcoin-cli -signet  -rpcwallet=playground-wallet -named sendtoaddress address="$PLAY_BITCOIN_ADDRESS" amount=0.00001$count$j fee_rate=2 comment=$TIME-$count-$k-$j ) > /dev/null 2>&1
echo "{ \"TXHASH\": \"$TXHASH\" }," > /dev/null 2>&1

echo LINE 94
#UNAMED
TXHASH=$(bitcoin-cli  -signet -rpcwallet=playground-wallet sendtoaddress "$PLAY_BITCOIN_ADDRESS"  0.00001$count$j -fallbackfee=0.00001 ) > /dev/null 2>&1
echo "{ \"TXHASH\": \"$TXHASH\" }," > /dev/null 2>&1
#NAMED
TXHASH=$(bitcoin-cli -signet  -rpcwallet=playground-wallet -named sendtoaddress address="$PLAY_BITCOIN_ADDRESS" amount=0.0000$count$j fee_rate=3 comment=$TIME-$count-$k-$j ) > /dev/null 2>&1
echo "{ \"TXHASH\": \"$TXHASH\" }," > /dev/null 2>&1

echo LINE 102
#UNAMED
TXHASH=$(bitcoin-cli -signet  -rpcwallet=playground-wallet sendtoaddress "$PLAY_BITCOIN_ADDRESS"  0.00001$count$j -fallbackfee=0.00001 ) > /dev/null 2>&1
echo "{ \"TXHASH\": \"$TXHASH\" }," > /dev/null 2>&1
#NAMED
TXHASH=$(bitcoin-cli -signet  -rpcwallet=playground-wallet -named sendtoaddress address="$PLAY_BITCOIN_ADDRESS" amount=0.00001$count$j fee_rate=4 comment=$TIME-$count-$k-$j ) > /dev/null 2>&1
echo "{ \"TXHASH\": \"$TXHASH\" }," > /dev/null 2>&1

echo LINE 110
#play-bitcoin 'bitcoin-cli -signet -rpcwallet=playground-wallet settxfee 0.0000$count$k$j'
play-bitcoin sendtoaddress playground-wallet $SELF_ADDRESS 0.0001 -fallbackfee=0.00001
play-bitcoin sendtoaddress playground-wallet $SELF_ADDRESS 0.0001 -fallbackfee=0.0001
play-bitcoin sendtoaddress playground-wallet $SELF_ADDRESS 0.0001 -fallbackfee=0.001
play-bitcoin sendtoaddress playground-wallet $SELF_ADDRESS 0.0001 -fallbackfee=0.01
play-bitcoin sendtoaddress playground-wallet $SELF_ADDRESS 0.0001 -fallbackfee=0.1
play-bitcoin sendtoaddress playground-wallet $SELF_ADDRESS 0.0001 -fallbackfee=0.01
play-bitcoin sendtoaddress playground-wallet $SELF_ADDRESS 0.001  -fallbackfee=0.001
play-bitcoin sendtoaddress playground-wallet $SELF_ADDRESS 0.01   -fallbackfee=0.0001
play-bitcoin sendtoaddress playground-wallet $SELF_ADDRESS 0.1    -fallbackfee=0.00001

}
end_time(){
echo "{ \"END_TIME\": $(date +%s) }]}"
}
################################################################################
for (( i = 1; i <= 200; i++ ))    ### i loop
do
    export i
    for (( j = 1 ; j <= 9; j++ )) ### j loop
    do
        export j
            padtowidth=$j
            for z in 0 {1..3} {3..5}; do
                k=$(printf "%0*d\n" $padtowidth $z;)
                export k
                #echo "},"
                echo "{ \"inner-loop\": ["
                #trap1
                trap 'end_time; exit' SIGINT SIGQUIT
                count=0
                while :
                do
                    sleep 1
                    count=$(expr $count + 1)
                    export count
                    echo "{ \"count\": \"$count\" },"
                    echo "{ \"i\": \"$i\" },"
                    echo "{ \"j\": \"$j\" },"
                    echo "{ \"k\": \"$k\" },"

                    host-cli-automate
                    echo $(bitcoin-cli  -signet -rpcwallet=playground-wallet getbalances),
                    echo $(play-bitcoin getbalances),

                done
        done
    done
done
blocknotify
#