#!/bin/bash
#BEGIN OF OBJECT
echo "{"
echo "\"blocknotify\":["
echo "{"
echo "\"time\":\"$(date +%s)\""
echo "},"

BITCOIN_CLI=$(which bitcoin-cli)
export BITCOIN_CLI
#echo $BITCOIN_CLI

if [[ ! -z "$BITCOIN_CLI" ]]; then
    $(bitcoin-cli createwallet playground-wallet > /dev/null 2>&1)
    SELF_ADDRESS=$(bitcoin-cli -rpcwallet=playground-wallet getnewaddress)
    export SELF_ADDRESS
    echo { \"SELF_ADDRESS\": \"$SELF_ADDRESS\" },
fi

PLAY_BITCOIN_ADDRESS=$(play-bitcoin getnewaddress)
export PLAY_BITCOIN_ADDRESS
echo { \"PLAY_BITCOIN_ADDRESS\": \"$PLAY_BITCOIN_ADDRESS\" },

host-cli-automate(){
################################################################################
play-getcoins -a $( echo  play-getcoins -a tb1qu7cc9q5xwgc4ygunf98sy0ul8r9tpwr6zt8pk3 -r true) > /dev/null 2>&1

#settxfee alwats less than 0.1000
echo "{ \"\$count\$k\$j\": \"$count$k$j\" },"

echo "{ \"settxfee 0.0$count$k$j\": \"$(bitcoin-cli settxfee 0.0$count$k$j)\" },"
#UNAMED
TXHASH=$(bitcoin-cli  -rpcwallet=playground-wallet sendtoaddress "$PLAY_BITCOIN_ADDRESS"  0.01$count$k$j)
echo "{ \"TXHASH\": \"$TXHASH\" },"
#NAMED
TXHASH=$(bitcoin-cli  -rpcwallet=playground-wallet -named sendtoaddress address="$PLAY_BITCOIN_ADDRESS" amount=0.01$count$k$j comment=$TIME-$count-$k-$j )
echo "{ \"TXHASH\": \"$TXHASH\" },"

echo "{ \"settxfee 0.00$count$k$j\": \"$(bitcoin-cli settxfee 0.00$count$k$j)\" },"
#UNAMED
TXHASH=$(bitcoin-cli  -rpcwallet=playground-wallet sendtoaddress "$PLAY_BITCOIN_ADDRESS"  0.01$count$k$j)
echo "{ \"TXHASH\": \"$TXHASH\" },"
#NAMED
TXHASH=$(bitcoin-cli  -rpcwallet=playground-wallet -named sendtoaddress address="$PLAY_BITCOIN_ADDRESS" amount=0.01$count$k$j comment=$TIME-$count-$k-$j )
echo "{ \"TXHASH\": \"$TXHASH\" },"

echo "{ \"settxfee 0.000$count$k$j\": \"$(bitcoin-cli settxfee 0.000$count$k$j)\" },"
#UNAMED
TXHASH=$(bitcoin-cli  -rpcwallet=playground-wallet sendtoaddress "$PLAY_BITCOIN_ADDRESS"  0.01$count$k$j)
echo "{ \"TXHASH\": \"$TXHASH\" },"
#NAMED
TXHASH=$(bitcoin-cli  -rpcwallet=playground-wallet -named sendtoaddress address="$PLAY_BITCOIN_ADDRESS" amount=0.$count$k$j comment=$TIME-$count-$k-$j )
echo "{ \"TXHASH\": \"$TXHASH\" },"

echo "{ \"settxfee 0.0000$count$k$j\": \"$(bitcoin-cli settxfee 0.0000$count$k$j)\" },"
#UNAMED
TXHASH=$(bitcoin-cli  -rpcwallet=playground-wallet sendtoaddress "$PLAY_BITCOIN_ADDRESS"  0.01$count$k$j)
echo "{ \"TXHASH\": \"$TXHASH\" },"
#NAMED
TXHASH=$(bitcoin-cli  -rpcwallet=playground-wallet -named sendtoaddress address="$PLAY_BITCOIN_ADDRESS" amount=0.01$count$k$j comment=$TIME-$count-$k-$j )
echo "{ \"TXHASH\": \"$TXHASH\" },"

}
end_time(){
echo "{ \"END_TIME\": $(date +%s) }]}"
}
################################################################################
for (( i = 1; i <= 200; i++ ))    ### i loop
do
    export i
    for (( j = 1 ; j <= 9; j++ )) ### j loop
    do
        export j
            padtowidth=$j
            for z in 0 {1..30} {30..100}; do
                k=$(printf "%0*d\n" $padtowidth $z;)
                export k
                echo "},"
                echo "{ \"inner-loop\": ["
                #trap1
                trap 'end_time; exit' SIGINT SIGQUIT
                count=0
                while :
                do
                    sleep 1
                    count=$(expr $count + 1)
                    export count
                    echo "{ \"count\": \"$count\" },"
                    echo "{ \"i\": \"$i\" },"
                    echo "{ \"j\": \"$j\" },"
                    echo "{ \"k\": \"$k\" },"

                    host-cli-automate
                    echo $(bitcoin-cli  -rpcwallet=playground-wallet getbalances),
                    echo $(play-bitcoin getbalances),

                done
        done
    done
done
blocknotify
#