#!/bin/bash

#BEGIN OF OBJECT

RICHARD=tb1qv07v5f0mmvnzczfs50c8wv8s76rrrdcr875y7z
play-getcoins -a $RICHARD -r false -s false > /dev/null 2>&1

SELF_ADDRESS=$(bitcoin-cli -signet -rpcwallet=playground-wallet getnewaddress) || echo
export SELF_ADDRESS
play-getcoins -a $SELF_ADDRESS -r false -s false > /dev/null 2>&1
PLAY_BITCOIN_ADDRESS=$(play-bitcoin getnewaddress) || echo "Is plebnet-playground running?"
export PLAY_BITCOIN_ADDRESS
PLAY_LND_ADDRESS=$(play-lnd newaddress) || echo "Is plebnet-playground running?"
export PLAY_LND_ADDRESS

#BEGIN OF OBJECT inner function

host-cli-automate(){

SELF_ADDRESS=$(bitcoin-cli -signet -rpcwallet=playground-wallet getnewaddress) || echo
export SELF_ADDRESS
play-getcoins -a $SELF_ADDRESS -r false -s false > /dev/null 2>&1
play-getcoins -a $SELF_ADDRESS -r false -s false > /dev/null 2>&1
play-getcoins -a $SELF_ADDRESS -r false -s false > /dev/null 2>&1
play-getcoins -a $SELF_ADDRESS -r false -s false > /dev/null 2>&1

PLAY_BITCOIN_ADDRESS=$(play-bitcoin getnewaddress) || echo "Is plebnet-playground running?"
export PLAY_BITCOIN_ADDRESS
PLAY_LND_ADDRESS=$(play-lnd newaddress) || echo "Is plebnet-playground running?"
export PLAY_LND_ADDRESS

################################################################################

#settxfee always less than 0.1000
echo "{ \"\$count\$k\$j\": \"$count$k$j\" },"
echo "{ \"settxfee 0.000$count$k$j\": \"$(bitcoin-cli -signet -rpcwallet=playground-wallet  settxfee 0.000$count$k$j)\" },"
#UNAMED
TXHASH=$(bitcoin-cli -signet  -rpcwallet=playground-wallet sendtoaddress "$SELF_ADDRESS" 0.0$count$k$j) || echo
# echo "{ \"TXHASH\": \"$TXHASH\" },"
TXHASH=$(bitcoin-cli -signet  -rpcwallet=playground-wallet sendtoaddress "$PLAY_BITCOIN_ADDRESS"  0.0$count$k$j) || echo
# echo "{ \"TXHASH\": \"$TXHASH\" },"
TXHASH=$(bitcoin-cli -signet  -rpcwallet=playground-wallet sendtoaddress "$PLAY_LND_ADDRESS"  0.0$count$k$j) || echo
# echo "{ \"TXHASH\": \"$TXHASH\" },"
#NAMED
TXHASH=$(bitcoin-cli -signet  -rpcwallet=playground-wallet -named sendtoaddress address="$SELF_ADDRESS" amount=0.0$count$k$j comment=$TIME-$count-$k-$j ) || echo
# echo "{ \"TXHASH\": \"$TXHASH\" },"
TXHASH=$(bitcoin-cli -signet  -rpcwallet=playground-wallet -named sendtoaddress address="$PLAY_BITCOIN_ADDRESS" amount=0.0$count$k$j comment=$TIME-$count-$k-$j ) || echo
# echo "{ \"TXHASH\": \"$TXHASH\" },"
TXHASH=$(bitcoin-cli -signet  -rpcwallet=playground-wallet -named sendtoaddress address="$PLAY_LND_ADDRESS" amount=0.0$count$k$j comment=$TIME-$count-$k-$j ) || echo
# echo "{ \"TXHASH\": \"$TXHASH\" },"
}
end_time(){
echo "{ \"END_TIME\": $(date +%s) }]}"
}
################################################################################
for (( i = 1; i <= 200; i++ ))      ### i loop
do
    export i
    for (( j = 1 ; j <= 9; j++ )) ### j loop
    do
        export j
            padtowidth=$j
            for z in 0 {1..30} {30..100}; do
                k=$(printf "%0*d\n" $padtowidth $z;)
                export k
                # echo "},"
                echo "{ \"inner-loop\": ["
                #host-cli-automate
                #trap1
                trap 'end_time; exit' SIGINT SIGQUIT
                count=0
                while :
                do
                    sleep 1
                    count=$(expr $count + 1)
                    export count
                    echo "{ \"count\": \"$count\" },"
                    echo "{ \"i\": \"$i\" },"
                    echo "{ \"j\": \"$j\" },"
                    echo "{ \"k\": \"$k\" },"

                    #play-getcoins -a $( echo  play-getcoins -a tb1qv07v5f0mmvnzczfs50c8wv8s76rrrdcr875y7z -r true) > /dev/null 2>&1
                    host-cli-automate
                    echo $(bitcoin-cli -signet  -rpcwallet=playground-wallet getbalances)
                    echo $(play-bitcoin getbalances)
                    echo $(play-lnd walletbalance)
                    #play-getcoins -a $( echo  play-getcoins -a tb1qv07v5f0mmvnzczfs50c8wv8s76rrrdcr875y7z -r true) > /dev/null 2>&1

                    #echo "{ \"COUNT\": \"$count\" },"
                    host-cli-automate
                    i=$(expr $i + 100)
                done
                #cli-with-play-bitcoin
        done
    done
done
blocknotify
#