#!/usr/bin/env bash

test -z "$(docker ps -q 2>/dev/null)" || $(docker ps -q 2>/dev/null | xargs -L1 docker stop) || echo "docker already stopped!"

function nuke-docker(){


echo -e "\n************ NUKE DOCKER *************"
echo      "************ NUKE DOCKER *************"
echo      "************ NUKE DOCKER *************"
echo -e   "************ NUKE DOCKER *************\n"

if hash systemctl 2>/dev/null; then
	if hash docker 2>/dev/null; then
		if hash apt-get 2>/dev/null; then
			sudo apt-get purge docker-ce docker-ce-cli containerd.io moby-engine moby-cli
		elif hash brew 2>/dev/null; then
			brew uninstall -f docker
		fi
	fi
fi

    sudo rm -rf /var/lib/docker

	if hash apt-get 2>/dev/null; then
		sudo apt-get install runc containerd
	elif hash brew 2>/dev/null; then
		echo $(which brew)
	fi

    curl -fsSL https://get.docker.com | sudo sh
    docker --version

    sudo rm -rf /etc/docker/daemon.json
    echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json

    if hash systemctl 2>/dev/null; then
        sudo systemctl restart docker
    fi
}
nuke-docker