name: plebnet-playground

# Controls when the action will run.
on:
  pull_request:
    branches:       #[ master ]
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - 'master'    # includes master
      - 'main'      # includes main
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    #paths:
    #  - '.github/workflows/automate.yml'
    #schedule:
    #  - cron: "*/5 * * * *"
    branches:       #[ master ]
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - 'master'    # includes master
      - 'main'      # includes main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-workspace:
    name: github-workspace
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, macos-10.15, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Print github workspace
        run: |
          printenv

  build_and_test_matrix:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest, macos-10.15, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: make initialize init help report
        run: |
          test -z "$(docker ps -q 2>/dev/null)" && $(docker ps -q 2>/dev/null | xargs -L1 docker stop) && $(osascript -e 'quit app "Docker"' || systemctl stop docker)
          make initialize init help report
          open --background -a Docker || systemctl restart docker
      - name: install, build, and test
        run: |
          make initialize init
          pip install -r docs/requirements.txt
          pip install -r requirements.txt
          make blocknotify
          make build nocache=true
          make build para=true
          make install verbose=true
      - name: play
        run: |
          play
          play info
          play ids
      - name: bitcoind-commands
        run: |
          play bitcoin
          play bitcoin top
          play bitcoin netinfo 5
          play bitcoin gettxoutsetinfo
          play bitcoin getmininginfo
          play bitcoin 'bitcoin-cli getblockhash 1000'
      - name: lnd-commands
        run: |
          # play defaults to the lnd container
          play lnd
          play lnd top
          play lnd lncli
          play lncli
          play lncli --version
          play lnd 'lncli --version'

      - name: uninstall
        run: |
          make uninstall

